spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  mybatis:
    mapper-locations: classpath:/mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true

# aws
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

# swagger
springdoc:
  swagger-ui:
    server-url: ${SWAGGER_URL}
    urls:
      - name: zippick
        url: ${SWAGGER_DOCS_URL}

# server health check
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  health:
    db:
      enabled: true

# logging
logging:
  level:
    root: INFO
    org.springframework: INFO
